logging:
    config: classpath:logback.xml
    level:
        com: debug
                   
mapper:
    identity: MYSQL
    mappers: com.wjwy.rsda.common.TkMapper
    not-empty: false
mybatis:
    configuration:
        map-underscore-to-camel-case: true
        mapUnderscoreToCamelCase: true
        useColumnLabel: true
    mapper-locations: classpath:mapper/**/*.xml
    type-aliases-package: com.wjwy.rsda.entity
pagehelper:
    helperDialect: mysql
    params: count=countSql
    reasonable: true
    supportMethodsArguments: true
server:
    port: 8080
    servlet:
        context-path: /
    tomcat:
        max-threads: 800
        min-spare-threads: 30
        uri-encoding: UTF-8
spring:
    datasource:
        driverClassName: com.mysql.jdbc.Driver
        druid:
            filter:
                stat:
                    enabled: true
                    log-slow-sql: true
                    merge-sql: true
                    slow-sql-millis: 1000
                wall:
                    config:
                        multi-statement-allow: true
            initialSize: 5
            maxActive: 20
            maxEvictableIdleTimeMillis: 900000
            maxWait: 60000
            minEvictableIdleTimeMillis: 300000
            minIdle: 10
            password: root
            statViewServlet:
                allow: ''
                enabled: true
                login-password: ''
                login-username: ''
                url-pattern: /druid/*
            testOnBorrow: false
            testOnReturn: false
            testWhileIdle: true
            timeBetweenEvictionRunsMillis: 60000
            url: jdbc:mysql://192.168.1.58:3306/crebas?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8
            username: root
            validationQuery: SELECT 1 FROM DUAL
            webStatFilter:
                enabled: true
        type: com.alibaba.druid.pool.DruidDataSource
    devtools:
        restart:
            enabled: true
    http:
        converters:
            preferred-json-mapper: jackson
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        joda-date-time-format: yyyy-MM-dd HH:mm:ss
        serialization:
            write-dates-as-timestamps: true
        time-zone: GMT+8
    messages:
        basename: static/i18n/messages
    profiles:
        active: druid
    session:
        store-type: none
    thymeleaf:
        cache: false
        encoding: utf-8
        mode: HTML
