#logback配置
logging:
  pattern:
    console: '%d -%msg%n'
  level:
    root: INFO
mapper:
    identity: MYSQL
    mappers: com.wjwy.rsda.common.TkMapper
    not-empty: false
mybatis:
    configuration:
        map-underscore-to-camel-case: true
        mapUnderscoreToCamelCase: true
        useColumnLabel: true
    mapper-locations: classpath:mapper/**/*.xml
    type-aliases-package: com.wjwy.rsda.entity
pagehelper:
    helperDialect: mysql
    params: count=countSql
    reasonable: true
    supportMethodsArguments: true
server:
    port: 8081
    tomcat:
        uri-encoding: UTF-8
spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.jdbc.Driver
        druid:
            # 主库数据源
             url: jdbc:mysql://192.168.1.58:3306/crebas?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
             username: root
             password: root
            # 初始连接数
             initialSize: 5
            # 最小连接池数量
             minIdle: 10
            # 最大连接池数量
             maxActive: 20
            # 配置获取连接等待超时的时间
             maxWait: 60000
            # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
             timeBetweenEvictionRunsMillis: 60000
            # 配置一个连接在池中最小生存的时间，单位是毫秒
             minEvictableIdleTimeMillis: 300000
            # 配置一个连接在池中最大生存的时间，单位是毫秒
             maxEvictableIdleTimeMillis: 900000
            # 配置检测连接是否有效
             validationQuery: SELECT 1 FROM DUAL
             testWhileIdle: true
             testOnBorrow: false
             testOnReturn: false
             webStatFilter: 
                enabled: true
             statViewServlet:
                enabled: true
                # 设置白名单，不填则允许所有访问
                allow:
                url-pattern: /druid/*
                # 控制台管理用户名和密码
                login-username: 
                login-password: 
             filter:
                stat:
                    enabled: true
                    # 慢SQL记录
                    log-slow-sql: true
                    slow-sql-millis: 1000
                    merge-sql: true
                wall:
                    config:
                        multi-statement-allow: true
    redis:
        host: 127.0.0.1
        port: 6379
        password : root
        timeout: 10000   
 
      
      
    session:
        store-type: none
    thymeleaf:
        cache: false
